language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - py.test --cov -v -r f
after_success:
  - bash <(curl -s https://codecov.io/bash)
