language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"
install:
  - pip install -e .
script:
  - py.test --cov
after_success:
  - bash <(curl -s https://codecov.io/bash)